import { BuildingConfig, UnitConfig, BuildingType, UnitType } from '../types';

export const MAP_SIZE = 80; // 80x80 tiles grid (Doubled map size)

export const PLAYERS_CONFIG: Record<number, {
  id: number;
  nameFa: string;
  nameEn: string;
  colorHex: number;
  colorCss: string;
  badgeBg: string;
  keepGridX: number;
  keepGridZ: number;
}> = {
  1: {
    id: 1,
    nameFa: 'تیم ۱ (شما - آبی)',
    nameEn: 'Player 1 (You - Blue)',
    colorHex: 0x2563eb,
    colorCss: '#2563eb',
    badgeBg: 'bg-blue-600',
    keepGridX: 12,
    keepGridZ: 64,
  },
  2: {
    id: 2,
    nameFa: 'تیم ۲ (شمال شرقی - قرمز)',
    nameEn: 'Player 2 (North East - Red)',
    colorHex: 0xef4444,
    colorCss: '#ef4444',
    badgeBg: 'bg-red-600',
    keepGridX: 64,
    keepGridZ: 12,
  },
  3: {
    id: 3,
    nameFa: 'تیم ۳ (شمال غربی - زرد)',
    nameEn: 'Player 3 (North West - Yellow)',
    colorHex: 0xf59e0b,
    colorCss: '#f59e0b',
    badgeBg: 'bg-amber-500',
    keepGridX: 12,
    keepGridZ: 12,
  },
  4: {
    id: 4,
    nameFa: 'تیم ۴ (جنوب شرقی - بنفش)',
    nameEn: 'Player 4 (South East - Purple)',
    colorHex: 0x8b5cf6,
    colorCss: '#8b5cf6',
    badgeBg: 'bg-purple-600',
    keepGridX: 64,
    keepGridZ: 64,
  },
};

export const INITIAL_RESOURCES = {
  gold: 300,
  wood: 200,
  stone: 150,
  food: 100,
  population: 2,
  maxPopulation: 10,
};

export const BUILDINGS_CONFIG: Record<BuildingType, BuildingConfig> = {
  keep: {
    type: 'keep',
    nameFa: 'دژ اصلی (مرکز فرماندهی)',
    nameEn: 'Main Keep',
    cost: { gold: 0, wood: 0, stone: 0 },
    hp: 2500,
    maxHp: 2500,
    descriptionFa: 'قلعه اصلی شما. در صورت نابودی، بازی باخت می‌شود.',
    icon: 'Castle',
    sizeX: 3,
    sizeZ: 3,
    populationGranted: 5,
  },
  house: {
    type: 'house',
    nameFa: 'خانه مسکونی',
    nameEn: 'House',
    cost: { gold: 30, wood: 25, stone: 0 },
    hp: 200,
    maxHp: 200,
    descriptionFa: 'سقف بالای سر کارگران. ظرفیت جمعیت شما را +۵ افزایش می‌دهد.',
    icon: 'Home',
    sizeX: 2,
    sizeZ: 2,
    populationGranted: 5,
  },
  farm: {
    type: 'farm',
    nameFa: 'مزرعه گندم',
    nameEn: 'Farm',
    cost: { gold: 40, wood: 30, stone: 0 },
    hp: 180,
    maxHp: 180,
    descriptionFa: 'تولیدکننده آذوقه (+۱۵ غذا هر ۵ ثانیه).',
    icon: 'Wheat',
    sizeX: 2,
    sizeZ: 2,
    resourceProduction: { food: 15 },
  },
  woodcutter: {
    type: 'woodcutter',
    nameFa: 'کارگاه چوب‌بری',
    nameEn: 'Woodcutter',
    cost: { gold: 45, wood: 10, stone: 0 },
    hp: 220,
    maxHp: 220,
    descriptionFa: 'تولید چوب از جنگل‌های اطراف (+۱۸ چوب هر ۵ ثانیه).',
    icon: 'Trees',
    sizeX: 2,
    sizeZ: 2,
    resourceProduction: { wood: 18 },
  },
  quarry: {
    type: 'quarry',
    nameFa: 'معدن سنگ',
    nameEn: 'Quarry',
    cost: { gold: 60, wood: 30, stone: 0 },
    hp: 300,
    maxHp: 300,
    descriptionFa: 'استخراج سنگ برای ساخت دژ و برج (+۱۵ سنگ هر ۵ ثانیه).',
    icon: 'Pickaxe',
    sizeX: 2,
    sizeZ: 2,
    resourceProduction: { stone: 15 },
  },
  goldmine: {
    type: 'goldmine',
    nameFa: 'معدن طلا',
    nameEn: 'Gold Mine',
    cost: { gold: 30, wood: 45, stone: 25 },
    hp: 280,
    maxHp: 280,
    descriptionFa: 'استخراج طلا از رگه‌های زیرزمینی (+۲۵ طلا هر ۵ ثانیه).',
    icon: 'Coins',
    sizeX: 2,
    sizeZ: 2,
    resourceProduction: { gold: 25 },
  },
  market: {
    type: 'market',
    nameFa: 'بازار و صرافی',
    nameEn: 'Market',
    cost: { gold: 70, wood: 20, stone: 20 },
    hp: 250,
    maxHp: 250,
    descriptionFa: 'جمع‌آوری مالیات و تجارت (+۲۵ طلا هر ۵ ثانیه).',
    icon: 'Coins',
    sizeX: 2,
    sizeZ: 2,
    resourceProduction: { gold: 25 },
  },
  barracks: {
    type: 'barracks',
    nameFa: 'پادگان (مرکز آموزش نیرو)',
    nameEn: 'Barracks',
    cost: { gold: 90, wood: 40, stone: 30 },
    hp: 500,
    maxHp: 500,
    descriptionFa: 'مرکز اصلی پادگان برای آموزش پیاده‌نظام، سواره‌نظام و تانک‌های سنگین رزمی.',
    icon: 'Swords',
    sizeX: 3,
    sizeZ: 3,
  },
  tower: {
    type: 'tower',
    nameFa: 'برج دیده‌بانی و دفاعی',
    nameEn: 'Watchtower',
    cost: { gold: 70, wood: 20, stone: 40 },
    hp: 550,
    maxHp: 550,
    descriptionFa: 'پرتاب خودکار تیر به سمت دشمنان در محدوده.',
    icon: 'TowerControl',
    sizeX: 2,
    sizeZ: 2,
    attackDamage: 24,
    attackRange: 7.5,
  },
  wall: {
    type: 'wall',
    nameFa: 'دیوار سنگین دفاعی',
    nameEn: 'Stone Wall',
    cost: { gold: 10, wood: 0, stone: 15 },
    hp: 400,
    maxHp: 400,
    descriptionFa: 'دیوار محکم برای سد کردن مسیر مهاجمان دشمن.',
    icon: 'Shield',
    sizeX: 1,
    sizeZ: 1,
  },
};

export const UNITS_CONFIG: Record<UnitType, UnitConfig> = {
  swordsman: {
    type: 'swordsman',
    nameFa: 'سرباز پیاده کلاشینکف',
    nameEn: 'Assault Rifleman',
    isEnemy: false,
    cost: { gold: 35, wood: 10, stone: 0, food: 10 },
    hp: 150,
    maxHp: 150,
    damageToUnits: 25,
    damageToBuildings: 30,
    attackRange: 5.5,
    attackSpeed: 1.3,
    moveSpeed: 2.3,
    icon: 'Sword',
    descriptionFa: 'سرباز پیاده با اسلحه اتوماتیک. با فاصله مناسب از دشمن شلیک مداوم انجام می‌دهد.',
    isRanged: true,
  },
  spearman: {
    type: 'spearman',
    nameFa: 'سرباز دوش‌پرتاب RPG',
    nameEn: 'RPG Anti-Armor Soldier',
    isEnemy: false,
    cost: { gold: 60, wood: 20, stone: 10, food: 15 },
    hp: 160,
    maxHp: 160,
    damageToUnits: 45,
    damageToBuildings: 90,
    attackRange: 7.0,
    attackSpeed: 0.9,
    moveSpeed: 2.1,
    icon: 'Milestone',
    descriptionFa: 'سرباز ضد زره مسلح به راکت‌انداز دوش‌پرتاب مستقیم علیه تانک‌ها و سازه‌ها.',
    isRanged: true,
  },
  archer: {
    type: 'archer',
    nameFa: 'تک‌تیرانداز اسنایپر',
    nameEn: 'Sniper Marksman',
    isEnemy: false,
    cost: { gold: 55, wood: 25, stone: 0, food: 10 },
    hp: 90,
    maxHp: 90,
    damageToUnits: 60,
    damageToBuildings: 15,
    attackRange: 11.5,
    attackSpeed: 0.7,
    moveSpeed: 2.5,
    icon: 'Target',
    descriptionFa: 'تک‌تیرانداز با اسلحه دوربین‌دار. شلیک بسیار دقیق و مرگبار از فاصله خیلی دور.',
    isRanged: true,
  },
  knight: {
    type: 'knight',
    nameFa: 'دوش‌پرتاب دوربرد (توپخانه‌ای)',
    nameEn: 'Long-Range Mortar RPG',
    isEnemy: false,
    cost: { gold: 110, wood: 35, stone: 25, food: 20 },
    hp: 210,
    maxHp: 210,
    damageToUnits: 40,
    damageToBuildings: 130,
    attackRange: 13.0,
    attackSpeed: 0.6,
    moveSpeed: 2.0,
    icon: 'Crown',
    descriptionFa: 'راکت‌انداز سنگین دوربرد. شلیک موشک‌های قوسی بر فراز موانع به سمت دژ و تانک‌ها.',
    isRanged: true,
  },
  tank: {
    type: 'tank',
    nameFa: 'تانک عادی',
    nameEn: 'Standard Battle Tank',
    isEnemy: false,
    cost: { gold: 240, wood: 90, stone: 70, food: 30 },
    hp: 600,
    maxHp: 600,
    damageToUnits: 75,
    damageToBuildings: 130,
    attackRange: 6.5,
    attackSpeed: 0.7,
    moveSpeed: 1.5,
    icon: 'Shield',
    descriptionFa: 'تانک غول‌پیکر با شلیک مستقیم توپ سنگین و زره پولادین مقاوم.',
    isRanged: true,
  },
  artillery_tank: {
    type: 'artillery_tank',
    nameFa: 'تانک دوربرد',
    nameEn: 'Long-Range Artillery Tank',
    isEnemy: false,
    cost: { gold: 280, wood: 120, stone: 100, food: 35 },
    hp: 350,
    maxHp: 350,
    damageToUnits: 55,
    damageToBuildings: 170,
    attackRange: 12.5,
    attackSpeed: 0.5,
    moveSpeed: 1.7,
    icon: 'Target',
    descriptionFa: 'تانک توپخانه دوربرد با گلوله‌های سنگین قوسی و ویرانگر علیه سازه‌های دوردست.',
    isRanged: true,
  },
  enemy_grunt: {
    type: 'enemy_grunt',
    nameFa: 'مهاجم وحشی',
    nameEn: 'Raider Grunt',
    isEnemy: true,
    cost: { gold: 0, wood: 0, stone: 0 },
    hp: 140,
    maxHp: 140,
    damageToUnits: 18,
    damageToBuildings: 26,
    attackRange: 1.1,
    attackSpeed: 1.1,
    moveSpeed: 2.2,
    icon: 'Skull',
    descriptionFa: 'سرباز پیاده متجاوز با تبر.',
    isRanged: false,
  },
  enemy_archer: {
    type: 'enemy_archer',
    nameFa: 'کماندار متجاوز',
    nameEn: 'Enemy Archer',
    isEnemy: true,
    cost: { gold: 0, wood: 0, stone: 0 },
    hp: 85,
    maxHp: 85,
    damageToUnits: 15,
    damageToBuildings: 8,
    attackRange: 6.0,
    attackSpeed: 1.0,
    moveSpeed: 2.4,
    icon: 'Target',
    descriptionFa: 'کماندار دشمن.',
    isRanged: true,
  },
  enemy_boss: {
    type: 'enemy_boss',
    nameFa: 'سرکرده متجاوزین (غول)',
    nameEn: 'Warlord Boss',
    isEnemy: true,
    cost: { gold: 0, wood: 0, stone: 0 },
    hp: 850,
    maxHp: 850,
    damageToUnits: 65,
    damageToBuildings: 95,
    attackRange: 1.6,
    attackSpeed: 0.9,
    moveSpeed: 1.6,
    icon: 'Flame',
    descriptionFa: 'فرمانده قدرتمند با تبر غول‌آسا و تخریب فوق‌العاده سازه‌ها.',
    isRanged: false,
  },
};

export interface WaveDefinition {
  waveIndex: number;
  timeToStartSec: number;
  grunts: number;
  archers: number;
  bosses: number;
  titleFa: string;
}

export const WAVE_SCHEDULE: WaveDefinition[] = [
  { waveIndex: 1, timeToStartSec: 45, grunts: 3, archers: 1, bosses: 0, titleFa: 'موج ۱: شبیخون کوچک' },
  { waveIndex: 2, timeToStartSec: 50, grunts: 5, archers: 2, bosses: 0, titleFa: 'موج ۲: یورش مهاجمان' },
  { waveIndex: 3, timeToStartSec: 55, grunts: 8, archers: 4, bosses: 0, titleFa: 'موج ۳: محاصره اولیه' },
  { waveIndex: 4, timeToStartSec: 60, grunts: 12, archers: 6, bosses: 1, titleFa: 'موج ۴: ورود سرکرده دشمن' },
  { waveIndex: 5, timeToStartSec: 65, grunts: 18, archers: 10, bosses: 2, titleFa: 'موج ۵: حمله همه‌جانبه ارتش تاریکی' },
];
